services:
  nginx:
    image: nginx:1.23
    volumes:
      - ../03-react-vite-final/dist:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    ports:
      - "80:80"
      - "443:443"
  db-mysql:
    image: mysql:5.7.40
    restart: always
    environment:
      - MYSQL_DATABASE=jobhunter
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3307:3306"
    expose:
      - "3306"

  backend-spring:
    build:
      context: ../04-java-spring-final
      dockerfile: Dockerfile
    ports:
      - "8088:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/jobhunter
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - HOIDANIT_UPLOAD_FILE_BASE_URI=file:///uploads/
    depends_on:
      - db-mysql
    volumes:
      - ../upload-docker/:/uploads/
    # docker compose -p sontx-spring-rest up -d
